export let dummyData = [
    {
        id: 1,
        shiftStart: "11:00",
        shiftEnd: "19:00",
        daysWorked: "--TWRFY",
        firstName: "jane",
        lastName: "goodall",
        email: "jgoodall@work.com",
        EEID: "ccrcbland",
        meetings: "bi-weekly",
        meetingsDay: "wednesday",
        warnings: "written",
    },
    {
        id: 2,
        shiftStart: "11:00",
        shiftEnd: "19:00",
        daysWorked: "--TWRFY",
        firstName: "ashton",
        lastName: "fafo",
        email: "jgoodall@work.com",
        EEID: "ccrcbland",
        meetings: "bi-weekly",
        meetingsDay: "wednesday",
        warnings: "written",
    },
    {
        id: 3,
        shiftStart: "10:00",
        shiftEnd: "18:00",
        daysWorked: "--TWRFY",
        firstName: "abby",
        lastName: "broccoli",
        email: "jgoodall@work.com",
        EEID: "ccrcbland",
        meetings: "bi-weekly",
        meetingsDay: "wednesday",
        warnings: "written",
    },
    {
        id: 4,
        shiftStart: "13:00",
        shiftEnd: "21:00",
        daysWorked: "S-TW-FY",
        firstName: "teddy",
        lastName: "roosevelt",
        email: "jgoodall@work.com",
        EEID: "ccrcbland",
        meetings: "bi-weekly",
        meetingsDay: "wednesday",
        warnings: "written",
    },
    {
        id: 5,
        shiftStart: "06:00",
        shiftEnd: "15:00",
        daysWorked: "--TWRFY",
        firstName: "brock",
        lastName: "johnson",
        email: "jgoodall@work.com",
        EEID: "ccrcbland",
        meetings: "none",
        meetingsDay: "none",
        warnings: "written",
    },
    {
        id: 6,
        shiftStart: "06:00",
        shiftEnd: "15:00",
        daysWorked: "--TWRFY",
        firstName: "ashley",
        lastName: "bickers",
        email: "jgoodall@work.com",
        EEID: "ccrcbland",
        meetings: "bi-weekly",
        meetingsDay: "wednesday",
        warnings: "written",
    },
    {
        id: 7,
        shiftStart: "06:00",
        shiftEnd: "15:00",
        daysWorked: "--TWRFY",
        firstName: "zedbra",
        lastName: "georgiason",
        email: "jgoodall@work.com",
        EEID: "ccrcbland",
        meetings: "bi-weekly",
        meetingsDay: "wednesday",
        warnings: "written",
    },
    {
        id: 8,
        shiftStart: "14:00",
        shiftEnd: "23:00",
        daysWorked: "--TWRFY",
        firstName: "geniva",
        lastName: "convention",
        email: "jgoodall@work.com",
        EEID: "ccrcbland",
        meetings: "bi-weekly",
        meetingsDay: "wednesday",
        warnings: "written",
    },
    {
        id: 9,
        shiftStart: "15:00",
        shiftEnd: "02:00",
        daysWorked: "--TWRFY",
        firstName: "thomas",
        lastName: "crickethall",
        email: "jgoodall@work.com",
        EEID: "ccrcbland",
        meetings: "bi-weekly",
        meetingsDay: "wednesday",
        warnings: "written",
    },
    {
        id: 10,
        shiftStart: "15:00",
        shiftEnd: "02:00",
        daysWorked: "--TWRFY",
        firstName: "patty",
        lastName: "headbetter",
        email: "jgoodall@work.com",
        EEID: "ccrcbland",
        meetings: "bi-weekly",
        meetingsDay: "wednesday",
        warnings: "written",
    },
];
